---
title: "enrichment_plot"
author: "Jason Torres"
date: "June 3, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setup libraries and directories 

```{r}
"%&%" <- function(a,b) paste0(a,b) 
library("dplyr")
library("data.table")
library("ggplot2")
library("gridExtra")

serv.dir <- "/Users/jtorres/FUSE/"
fgwas.dir <- serv.dir %&% "projects/t2d-integration/fgwas/diagram_hrc/"
fgwas.out.dir <- fgwas.dir %&% "fgwas_output/"



```

# Processing function 

```{r}

annot_process <- function(fname){
  df <- fread(fname)
  df$CI_lo <- gsub("<","",df$CI_lo); df$CI_lo <- gsub("fail",NA,df$CI_lo); df$CI_lo <- as.numeric(df$CI_lo)
  df$CI_hi <- gsub(">","",df$CI_hi); df$CI_hi <- gsub("fail",NA,df$CI_hi); df$CI_hi <- as.numeric(df$CI_hi)
  return(df)
}

```

# Individual Analyses 

```{r}


build_param_df <- function(name.vec=NULL){
  files <- list.files(fgwas.out.dir)
  param.files <- files[grepl(".params",files,fixed=TRUE)]
  param.files <- param.files[!grepl("+",param.files,fixed=TRUE)]
  param.files <- param.files[!grepl("drop",param.files,fixed=TRUE)]  
  out.df <- c()
  for (f in param.files){
    stack.df <- annot_process(fgwas.out.dir%&%f)
    out.df <- rbind(out.df,stack.df)
  }
  out.df <- filter(out.df,parameter!="pi_region")
  out.df <- arrange(out.df,desc(estimate))
  enriched <- filter(out.df, CI_lo>0,estimate>0,CI_hi>0)
  depleted <- filter(out.df, CI_lo<0,estimate<0,CI_hi<0)
  print("There are " %&% dim(out.df)[1] %&% " annotations")
  print("There are " %&% dim(enriched)[1] %&% " annotations that are marginally ENRICHED")
  print("There are " %&% dim(depleted)[1] %&% " annotations that are marginally DEPLETED")
  out.df <- rbind(enriched,depleted)
  if (!is.null(name.vec)){
    out.df$parameter<-name.vec
  }
  return(out.df)
}


build_param_best_df <- function(pre,name.vec=NULL){
  # Note: pre is best model from fgwas run 
  # Example: 
    #pre <- fgwas.out.dir %&% "drop-islet_state11+islet_state6+islet_state12+utr_5+" %&%
    #"islet_stretch_enhancer+promoter+distance_tss+islet_state9"
  param.df <- annot_process(pre %&% ".params")
  param.df <- arrange(param.df,desc(estimate))
  param.df <- filter(param.df,parameter!="pi")
  param.df <- filter(param.df,parameter!="pi_region")

  if (!is.null(name.vec)){
    param.df$parameter<-name.vec
  }
  return(param.df)
}

```


# Annotation plot 

```{r}


an_plot <- function(mydf,mytitl="",mylow=-10,myhigh=10,interval=1){
  mydf <- within(mydf,parameter<-factor(mydf$parameter,levels=rev(mydf$parameter)))
  mydf <- filter(mydf,parameter!="pi_region")
  plt <- ggplot(data=mydf,aes(x=parameter,y=estimate)) + 
    #geom_col(col="black",aes(fill=(estimate>0))) + coord_flip() + 
      geom_hline(yintercept=0,linetype=2) +
    ylab("Log2FE") + xlab("Annotation") + 
    geom_errorbar(aes(ymin=CI_lo,ymax=CI_hi),width=0.1) + 
    geom_point(shape=21,size=1.5,col="black",aes(fill=(estimate>0)))  +
    scale_fill_manual(values=c("steelblue1","firebrick1")) + 
    theme_bw()  +  theme(legend.position = "none",
                         panel.grid.minor=element_blank(),
                         panel.grid.major=element_blank()) + 
    scale_y_continuous(breaks=seq(mylow,myhigh,by=interval)) + 
    coord_flip(ylim=c(mylow,myhigh)) + 
    ggtitle(mytitl)
  return(plt)
}




```

# Generate plot 1 : Individual annotations that individually meet marginal significance (confidence intervals not overlapping zero) 

```{r}

param.sing.df <- build_param_df()
plt1 <- an_plot(param.sing.df,mytitl="DIAGRAM (HRC Imputation): Seperate Analysis",mylow=-5,myhigh=5,interval=1)
ggsave(filename=fgwas.dir %&% "DIAGRAM-gwas" %&% ".fgwas_enrich.seperate.png",plot=plt1,width=6,height=6)

```

# Generate plot 2 : Joint analysis of annotations in the 'Best' model 

```{r}
mypre <- fgwas.out.dir %&% "drop-islet_state11+islet_state6+islet_state12+utr_5+" %&%
                                   "islet_stretch_enhancer+promoter+distance_tss+islet_state9"
param.df <- build_param_best_df(mypre,name.vec=c("Coding","Islet ATAC", "Islet Strong Enhancer",
                                                 "Islet Low DNA. Meth.","Islet Heterochrom.",
                                                 "Islet Polycomb. Rep."))
plt2 <- an_plot(param.df,mytitl="DIAGRAM (HRC Imputation): Joint Analysis",mylow=-5,myhigh=5,interval=1)
ggsave(filename=fgwas.dir %&% "DIAGRAM-gwas" %&% ".fgwas_enrich.joint.png",plot=plt2,width=6,height=6)

```


